power <- read.table("household_power_consumption.txt", header = TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
subpower <- subset(power, power$Date=="1/2/2007" | power$Date == "2/2/2007")
subpower$Date <- as.Date(subpower$Date, format="&d/%m/%Y")
subpower$Time <- strptime(subpower$Time, format="%H:%M:%S") 
plot(subpower$Time, subpower$Sub_metering_1, type="n", xlab=" ", ylab="Energy Sub Metering")
with(subpower, lines(Time, as.numeric(as.character(Sub_metering_1))))
with(subpower, lines(Time, as.numeric(as.character(Sub_metering_2)), col="red"))
with(subpower, lines(Time, as.numeric(as.character(Sub_metering_3)), col="blue"))
legend("topright", lty=1, col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
title(main="Energy sub-metering")
dev.off()
