power <- read.table("household_power_consumption.txt", header = TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
subdate <- power[power$Date %in% c("1/2/2007","2/2/2007"), ]
datewithtime <- strptime(paste(subdate$Date, subdate$Time, sep=""), "%d/%m/%Y %H:%M:%S")
globalactivepower <- as.numeric(subdate$Global_active_power)
globalreactivepower <- as.numeric(subdate$Global_reactive_power)
voltage <- as.numeric(subdate$Voltage)
submetering1 <- as.numeric(subdate$Sub_metering_1)
submetering2 <- as.numeric(subdate$Sub_metering_2)
submetering3 <- as.numeric(subdate$Sub_metering_3)
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(datewithtime, globalactivepower, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(datewithtime, voltage, type="l", xlab="date time", ylab = "Voltage")
plot(datewithtime, submetering1, type="l", xlab="", ylab = "Energy Submetering")
lines(datewithtime, submetering2, type="l", col="red")
lines(datewithtime, submetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lwd=2.5, col=c("black","red","blue"), bty="o")
plot(datewithtime, globalreactivepower, type="l", xlab="date time", ylab = "Global_reactive_power")
dev.off()
